# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-mcp" do
  version "0.4.1"

  on_macos do
    on_intel do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_amd64.tar.gz"
      sha256 "f7995ac875862d404703748747e7462b8a28ef4c8fa9ba4419dbb13eb7a591ad"
    end
    on_arm do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_arm64.tar.gz"
      sha256 "cfbeb3a5b6e5e1c94e5b975de0ebedeae545ed248d8849482d05c0a843be29f1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_amd64.tar.gz"
      sha256 "d3d5a15fc889b57ef5943211c822050213b8297bf87ff8ebb53661c994f5b098"
    end
    on_arm do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_arm64.tar.gz"
      sha256 "910495b1784802679afb9ddd55a5930128112deb99db570c67c76b4a72f757da"
    end
  end

  name "jira-mcp"
  desc "JIRA MCP server — give your AI assistant full JIRA access"
  homepage "https://github.com/mmatczuk/jira-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jira-mcp"]
    end
  end

  # No zap stanza required

end
