# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-mcp" do
  name "jira-mcp"
  desc "JIRA MCP server — give your AI assistant full JIRA access"
  homepage "https://github.com/mmatczuk/jira-mcp"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira-mcp"

  on_macos do
    on_intel do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_amd64.tar.gz"
      sha256 "eee6480bfe0289bc4925bfee169f8753ee7dba6d078184f6d0db45da4cbfafba"
    end
    on_arm do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_arm64.tar.gz"
      sha256 "2aa38c5fa3695d74f535438968351f7685b580a8bac941b394861ba30f823d70"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_amd64.tar.gz"
      sha256 "a86c828a65e0d4db4d3c31d18c2f82c5d28b6e2e91a3cfb6c9607999cd3801b0"
    end
    on_arm do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_arm64.tar.gz"
      sha256 "20a87772dc01da7febd4bde899b6e1d5865056fc31039de50d5a453bf3f76c29"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jira-mcp"]
    end
  end

  # No zap stanza required
end
